import type { Professional } from "@/components/ProfessionalCard";

export const professionals: Professional[] = [
  {
    id: "ana-ribeiro",
    name: "Dra. Ana Ribeiro",
    pronoun: "ela/dela",
    specialty: "Psicologia · Saúde Mental LGBTQIAPN+",
    rating: 4.9,
    reviews: 187,
    distance: "1,2 km",
    online: true,
    inPerson: true,
    acceptsSus: false,
    acceptsInsurance: true,
    city: "São Paulo, SP",
    inclusionScore: 98,
    badges: ["Pessoas trans", "Saúde mental"],
    avatarGradient: "linear-gradient(135deg,#6C63FF,#3B82F6)",
    initials: "AR",
  },
  {
    id: "lucas-mendes",
    name: "Dr. Lucas Mendes",
    pronoun: "ele/dele",
    specialty: "Infectologia · PrEP/PEP",
    rating: 4.8,
    reviews: 142,
    distance: "2,8 km",
    online: true,
    inPerson: true,
    acceptsSus: true,
    acceptsInsurance: true,
    city: "São Paulo, SP",
    inclusionScore: 96,
    badges: ["PrEP", "ISTs"],
    avatarGradient: "linear-gradient(135deg,#14B8A6,#3B82F6)",
    initials: "LM",
  },
  {
    id: "iris-vasconcelos",
    name: "Dre. Íris Vasconcelos",
    pronoun: "elu/delu",
    specialty: "Endocrinologia · Hormonioterapia",
    rating: 5.0,
    reviews: 96,
    distance: "4,1 km",
    online: true,
    inPerson: false,
    acceptsSus: false,
    acceptsInsurance: true,
    city: "Rio de Janeiro, RJ",
    inclusionScore: 99,
    badges: ["Hormonioterapia", "Pessoas trans"],
    avatarGradient: "linear-gradient(135deg,#8B5CF6,#EC4899)",
    initials: "IV",
  },
  {
    id: "rafael-souza",
    name: "Dr. Rafael Souza",
    pronoun: "ele/dele",
    specialty: "Clínico Geral · Saúde Sexual",
    rating: 4.7,
    reviews: 211,
    distance: "0,8 km",
    online: false,
    inPerson: true,
    acceptsSus: true,
    acceptsInsurance: true,
    city: "São Paulo, SP",
    inclusionScore: 92,
    badges: ["Saúde sexual"],
    avatarGradient: "linear-gradient(135deg,#3B82F6,#14B8A6)",
    initials: "RS",
  },
  {
    id: "marina-tavares",
    name: "Dra. Marina Tavares",
    pronoun: "ela/dela",
    specialty: "Ginecologia inclusiva",
    rating: 4.9,
    reviews: 168,
    distance: "3,5 km",
    online: true,
    inPerson: true,
    acceptsSus: false,
    acceptsInsurance: true,
    city: "Belo Horizonte, MG",
    inclusionScore: 95,
    badges: ["Pessoas trans", "Saúde sexual"],
    avatarGradient: "linear-gradient(135deg,#EC4899,#6C63FF)",
    initials: "MT",
  },
  {
    id: "joao-pedro",
    name: "João Pedro Alves",
    pronoun: "ele/dele",
    specialty: "Psicoterapia · Neurodivergências",
    rating: 4.8,
    reviews: 73,
    distance: "Online",
    online: true,
    inPerson: false,
    acceptsSus: false,
    acceptsInsurance: false,
    city: "Atendimento online",
    inclusionScore: 94,
    badges: ["Saúde mental", "Neurodivergência"],
    avatarGradient: "linear-gradient(135deg,#14B8A6,#6C63FF)",
    initials: "JA",
  },
];

export const specialties = [
  { name: "Saúde Mental", icon: "Brain", count: 248, tone: "primary" as const },
  { name: "Saúde Sexual", icon: "HeartPulse", count: 184, tone: "accent" as const },
  { name: "Hormonioterapia", icon: "Pill", count: 92, tone: "teal" as const },
  { name: "PrEP & PEP", icon: "ShieldCheck", count: 64, tone: "primary" as const },
  { name: "Ginecologia inclusiva", icon: "Stethoscope", count: 76, tone: "accent" as const },
  { name: "Endocrinologia", icon: "Activity", count: 58, tone: "teal" as const },
  { name: "Clínica Geral", icon: "Cross", count: 312, tone: "primary" as const },
  { name: "Nutrição", icon: "Salad", count: 121, tone: "accent" as const },
];

export const articles = [
  {
    id: "1",
    category: "Saúde Mental",
    title: "Como construir uma rede de apoio segura na sua jornada",
    excerpt: "Cinco passos para encontrar pessoas, espaços e profissionais que respeitam quem você é.",
    readTime: "6 min",
    gradient: "linear-gradient(135deg,#6C63FF,#3B82F6)",
  },
  {
    id: "2",
    category: "PrEP",
    title: "PrEP, PEP e prevenção combinada: o que você precisa saber",
    excerpt: "Entenda quando, como e por que essas estratégias salvam vidas — sem julgamento.",
    readTime: "8 min",
    gradient: "linear-gradient(135deg,#14B8A6,#3B82F6)",
  },
  {
    id: "3",
    category: "Hormonioterapia",
    title: "Início da hormonioterapia: o que esperar dos primeiros meses",
    excerpt: "Mudanças, cuidados e direitos garantidos por lei para pessoas trans e não-binárias.",
    readTime: "10 min",
    gradient: "linear-gradient(135deg,#8B5CF6,#EC4899)",
  },
];
